version: "3.8"

services:
  shoe-sales-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BASE_URL_API: "${BASE_URL_API}"
    ports:
      - 3000:3000
    volumes:
      - app-volume:/app
    working_dir: /app

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB: "${PGDATABASE}"
    ports:
      - 5442:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD}"
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  app-volume:
